version: '3.4'

services:
  ticketstore.web:    
    build:
      context: .
      dockerfile: TicketStore.Client/Dockerfile
    environment:
      - ApiConfigs__EventCatalog__Uri=http://ticketstore.services.eventcatalog
      - ApiConfigs__ShoppingBasket__Uri=http://ticketstore.services.shoppingbasket
      - ApiConfigs__Discount__Uri=http://ticketstore.services.discount
      - ApiConfigs__Order__Uri=http://ticketstore.services.order
      - ApiConfigs__Marketing__Uri=http://ticketstore.services.marketing 

  ticketstore.services.eventcatalog:
    build:
      context: .
      dockerfile: TicketStore.Services.EventCatalog/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=TicketStoreEventCatalogDb;Integrated Security=False;User ID=sa;Password=P(ssw0rd0123);Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;
    depends_on:
      - db

  ticketstore.services.shoppingbasket:
    build:
      context: .
      dockerfile: TicketStore.Services.ShoppingBasket/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=TicketStoreShoppingBasketDb;Integrated Security=False;User ID=sa;Password=P(ssw0rd0123);Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;
      - ApiConfigs__EventCatalog__Uri=http://ticketstore.services.eventcatalog
    depends_on:
      - db
  
  external.paymentgateway:
    build:
      context: .
      dockerfile: External.PaymentGateway/Dockerfile


  ticketstore.web.bff:
    build:
      context: .
      dockerfile: TicketStore.Web.Bff/Dockerfile


  ticketstore.gateway.mobilebff:
    build:
      context: .
      dockerfile: TicketStore.Gateway.MobileBff/Dockerfile


  ticketstore.gateway.webbff:
    build:
      context: .
      dockerfile: TicketStore.Gateway.WebBff/Dockerfile


  ticketstore.services.discount:
    build:
      context: .
      dockerfile: TicketStore.Services.Discount/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=TicketStoreDiscountDB;Integrated Security=False;User ID=sa;Password=P(ssw0rd0123);Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;
    depends_on:
      - db
  


  ticketstore.services.marketing:
    build:
      context: .
      dockerfile: TicketStore.Services.Marketing/Dockerfile
    environment:
      - ApiConfigs__ShoppingBasket__Uri=http://ticketstore.services.shoppingbasket
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=TicketStoreMarketingDb;Integrated Security=False;User ID=sa;Password=P(ssw0rd0123);Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;

  ticketstore.services.ordering:
    build:
      context: .
      dockerfile: TicketStore.Services.Order/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=TicketStoreOrderingDB;Integrated Security=False;User ID=sa;Password=P(ssw0rd0123);Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;
      - ServiceBusConnectionString=Endpoint=sb://vic-servicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Z0aDrpGGxqeZYyBieNuaf8pId8mkKllIG+ASbPNUS6o=;TransportType=NetMessaging
      - CheckoutMessageTopic=checkoutmessage
      - OrderPaymentRequestMessageTopic=orderpaymentrequestmessage
      - OrderPaymentUpdatedMessageTopic=orderpaymentupdatedmessage
    depends_on:
      - db

  ticketstore.services.payment:
    build:
      context: .
      dockerfile: TicketStore.Services.Payment/Dockerfile
    environment:
      - ServiceBusConnectionString=Endpoint=sb://vic-servicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Z0aDrpGGxqeZYyBieNuaf8pId8mkKllIG+ASbPNUS6o=;TransportType=NetMessaging
      - subscriptionName=ticketstorepayment
      - OrderPaymentRequestMessageTopic=orderpaymentrequestmessage
      - OrderPaymentUpdatedMessageTopic=orderpaymentupdatedmessage
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    expose:
     - "1433"
    ports:
     - "1434:1433"
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=P(ssw0rd0123)


